export const config = {
  MINIO_ENDPOINT: '193.124.113.0',
  MINIO_PORT: 9000,
  MINIO_ACCESSKEY: 'AKIAIOSFODNN7EXAMPLE',
  MINIO_SECRETKEY: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY',
  MINIO_BUCKET: 'main',
}
